# Generated by Django 3.2 on 2021-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True)),
                ('http_host', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.FileField(blank=True, null=True, upload_to='meta_data_files/')),
                ('city_data', models.FileField(blank=True, null=True, upload_to='city_data_files/')),
                ('anonymous_ip_data', models.FileField(blank=True, null=True, upload_to='anonymous_ip_data_files/')),
                ('asn_data', models.FileField(blank=True, null=True, upload_to='asn_data_files/')),
                ('connection_type_data', models.FileField(blank=True, null=True, upload_to='connection_type_data_files/')),
                ('domain_data', models.FileField(blank=True, null=True, upload_to='domain_data_files/')),
                ('enterprise_data', models.FileField(blank=True, null=True, upload_to='enterprise_data_files/')),
                ('isp_data', models.FileField(blank=True, null=True, upload_to='isp_data_files/')),
            ],
        ),
    ]
